baseurl = "https://markboss.de/"
languageCode = "en-us"
title = "Mark Boss"
theme = "Epilog"
googleAnalytics = "UA-43526609-4"

canonifyurls = true
paginate = 10

[[menu.main]]
  name = "Recipe"
  identifier = "Recipe"
  url = "/recipe/"
[[menu.main]]
    name = "Basics"
    identifier = "basics"
    url = "/categories/basics/"
    parent = "Recipe"
[[menu.main]]
    name = "Appetizer"
    identifier = "appetizer"
    url = "/categories/appeitzer/"
    parent = "Recipe"
[[menu.main]]
    name = "Main Dish"
    identifier = "main-dish"
    url = "/categories/main-dish/"
    parent = "Recipe"
[[menu.main]]
    name = "Desert"
    identifier = "desert"
    url = "/categories/desert/"
    parent = "Recipe"
[[menu.main]]
  name = "Programming"
  identifier = "programming"
  url = "/programming/"
[[menu.main]]
  name = "Design"
  identifier = "design"
  url = "/design/"
[[menu.main]]
  name = "Productivity"
  identifier = "productivity"
  url = "/productivity"

[params]
        title = "Mark Boss"
        copyright = "Copyright (c), Mark Boss; all rights reserved."

        name = "Mark Boss"
        description = "A blog about vegan cooking, programming, design and random stuff"
        twitter = "benediktmboss"
        github = "vork"
        instagram = "benediktmboss"

        keepReadingStr = "Keep reading"
