baseurl = "https://markboss.de/"
languageCode = "en-us"
title = "Mark Boss"
theme = "steam"

canonifyurls = true
paginate = 10

[[menu.main]]
  name = "Receipes"
  identifier = "receipe"
  url = "/receipe/"
[[menu.main]]
  name = "Programming"
  identifier = "programming"
  url = "/programming/"
[[menu.main]]
  name = "Design"
  identifier = "design"
  url = "/design/"

[params]
        title = "Mark Boss"
        subtitle = "A blog about vegan cooking, programming, design and random stuff"
        copyright = "Copyright (c) 2016 - 2016, Mark Boss; all rights reserved."
        themeColor = "blue"

        name = "Mark Boss"
        bio = "Nerd, cooking enthusiast"
        description = "A blog about vegan cooking, programming, design and random stuff"
        twitter = "benediktmboss"
        github = "vork"

        keepReadingStr = "Keep reading"
	      backtotopStr = "Back to top"
	      shareStr = "Share"
	      pageNotFoundTitle = "404 - Page not found"
