baseurl = "https://markboss.de/"
languageCode = "en-us"
title = "Mark Boss - a blog about vegan cooking, programming and stuff"
theme = "type"
copyright = "Copyright (c) 2016 - 2016, Mark Boss; all rights reserved."
canonifyurls = true
paginate = 5

[[menu.main]]
  name = "Receipes"
  identifier = "receipe"
  url = "/receipe/"
[[menu.main]]
  name = "Programming"
  identifier = "programming"
  url = "/programming/"
[[menu.main]]
  name = "Design"
  identifier = "design"
  url = "/design/"

[params]
