baseurl = "https://markboss.de/"
languageCode = "en-us"
title = "Mark Boss"
theme = "Epilog"

canonifyurls = true
paginate = 10

[[menu.main]]
  name = "Receipe"
  identifier = "Receipe"
  url = "/receipe/"
[[menu.main]]
    name = "Basics"
    identifier = "basics"
    url = "/categories/basics/"
    parent = "Receipe"
[[menu.main]]
    name = "Appetizer"
    identifier = "appetizer"
    url = "/categories/appeitzer/"
    parent = "Receipe"
[[menu.main]]
    name = "Main Dish"
    identifier = "main-dish"
    url = "/categories/main-dish/"
    parent = "Receipe"
[[menu.main]]
    name = "Desert"
    identifier = "desert"
    url = "/categories/desert/"
    parent = "Receipe"
[[menu.main]]
  name = "Programming"
  identifier = "programming"
  url = "/programming/"
[[menu.main]]
  name = "Design"
  identifier = "design"
  url = "/design/"

[params]
        title = "Mark Boss"
        subtitle = "A blog about vegan cooking, programming, design and random stuff"
        copyright = "Copyright (c), Mark Boss; all rights reserved."
        themeColor = "blue"

        name = "Mark Boss"
        bio = "Nerd, cooking enthusiast"
        description = "A blog about vegan cooking, programming, design and random stuff"
        twitter = "benediktmboss"
        github = "vork"
        instagram = "benediktmboss"

        keepReadingStr = "Keep reading"
	      backtotopStr = "Back to top"
	      shareStr = "Share"
	      pageNotFoundTitle = "404 - Page not found"
